// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-30bt-sighIWKp9O1nDd8w4l7UErAs60',
    appId: '1:902025343441:web:cf9a26287c571ba6ccb0f0',
    messagingSenderId: '902025343441',
    projectId: 'massenger-1fba0',
    authDomain: 'massenger-1fba0.firebaseapp.com',
    storageBucket: 'massenger-1fba0.appspot.com',
    measurementId: 'G-R7RWW42S7N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3JDPY1uoYsxnzvmEOcEmx-Yct7lhbBos',
    appId: '1:902025343441:android:c07d804cea0e5728ccb0f0',
    messagingSenderId: '902025343441',
    projectId: 'massenger-1fba0',
    storageBucket: 'massenger-1fba0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVUMC3fDdSY62eGTclrOZJTNvO5_Ly58w',
    appId: '1:902025343441:ios:a635cb776405a83cccb0f0',
    messagingSenderId: '902025343441',
    projectId: 'massenger-1fba0',
    storageBucket: 'massenger-1fba0.appspot.com',
    iosBundleId: 'com.ali.massenger',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVUMC3fDdSY62eGTclrOZJTNvO5_Ly58w',
    appId: '1:902025343441:ios:955f05120e1a18b2ccb0f0',
    messagingSenderId: '902025343441',
    projectId: 'massenger-1fba0',
    storageBucket: 'massenger-1fba0.appspot.com',
    iosBundleId: 'com.example.massenger',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-30bt-sighIWKp9O1nDd8w4l7UErAs60',
    appId: '1:902025343441:web:e134e953f0a965b1ccb0f0',
    messagingSenderId: '902025343441',
    projectId: 'massenger-1fba0',
    authDomain: 'massenger-1fba0.firebaseapp.com',
    storageBucket: 'massenger-1fba0.appspot.com',
    measurementId: 'G-3RLYSZEHBT',
  );
}
